services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: kevinmathew
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Djkevink@2025
      - key: WEBHOOK_URL
        value: https://n8n-mathew.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
